apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCojrBsWyQmdh+pg6zkmyc0ahvp+lCFbvanoCjzpTfrg7FlRYwvp7NsVH/CgHj03ZTuvWZWe/YKl9/VpEIPD1Wf1qIeooAJBUe5G7cTgH+jKaTHXWxnTCRoSEY2KoVw4snMPYO00cDQHzzGhll++veUihCIIDYZioDUs0qpi8q9rtGdygJbHUAol86yXoHFKZdT451YCCZymSkfVdyt46SWxT4LmQCxRi6Z5Xh2nlwaKvLlR4rDHvgbBj0zadvXyZk4XCzCcSF/uAAcrVdTqA033+2W6eElXoepXhQ0CNSR+xn2Uf6KkbJLZiSFVeOBHTIVugvZceWxYaD65dRX8yeRkK7ARKF71B1fO5C0KjtGWAvziK4iwuqFv3m8wAxEYDv+bx86tZ4iOG8ccCjFgwAadY+5Z+HRTzoyHOHK08sLnBxcrAsWb2drV2lSLodlYvt5hfdAlnRE/1/nLA7g2ESUTpvnEWbtBrhl1jNgZUvO0rLeKCK873zfIdn1L/OoXZ0mp11bDag0UKyGGwcCBIOZfucVeTY9+O6nYbLsDtwzEpIcZDt/mJZ0kv5Fot5HwlDHyiKvA4dvl+hNj4TlE/qrwZNneDmxxyx6sbjM+DUsUT6tLyKDMYGDlwrCIDWo4popmuusvsPplHHX8C7a4rko2HBlmM/9XyhCGGIL/D3K5i4yp8AjO7WxxfmizkeFV2rZ+9/2g0d1o7HwhzTpI4VPoMUrbw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
