apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAfZ9w7bEWxyVIozvFerTWoOPPu2rAOyEcqN+oYxjAzwP50WQB3dBk2zlxVxgoWEafBerzyKBfexvfnVdZwzBl1el/I57Nr41aWL1QqcP7zmgjzSfNSJRgLHG5lw47q678Mxxr4afLcXmZiFscUYP1RseHE5pt/6HjzYLmfn5ereHzFk88fCBFJUwCa6DRT3vHTf0i1Oe2mAJL9fu3CZ/oULP2fxBWl4bwahukssSs1Oj31HMWrXrY5aqlxsbxFN5MDhLDKwjEPQKFhtGx0z8nhDUtKBmmSolpZwr5Gumuj/gW+MrMJCCqgpRG2VxfTzoqBuhIMGnBWC+3BqjBwmnFxYvpPvdQhd7usTH6Sq8N9I7nfui3/rz+T4w1RkxYFBDuPgzVouqs8NUBEoDoEInhrQ4eC8Qd5wUPeZaz/3sGQeczhoVZ/5oXcYW4XgDRjfH4lXNSd1Wx7s5CW8tKSK1K9sPf+X1Va5PSthIgEFhMG0mMp341CPHXeD11uLH4iQkHz4kzPSzJLJaWtOVJ8RfYRsHQ3e25AiuiJiBlgJtI1fOeD/KHmynN1S1nTYbcMzWwf5Z/pI1ZHQ9PKYjieJUAEDS2iCHzGH2y67jDgBdyrOmxm3L7Equ3ixu5Zgr4X+eafScUbKqmS+C5Jo7Mrhye++/IycawZXjAmcsdKgWghhkE3eOeDeMwzuPxBIKMZqXr7GPkZBqmRYzWY5LYq0ILcHrFNUA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
